### PR TITLE
Refactor to make adding new sites near-trivial, also Youtube

### PR DESCRIPTION
**Pull request by Firefly7-7**
Refactor of the codebase to make adding a new site only require 1 new line of code, to make some messages more verbose, and to make the tracker remover able to differentiate between necessary/harmless parameters and trackers using a provided regex.

I also added Youtube.

### CODE REVIEW

**Comment by Firefly7-7** [comment]
I tried to do the steps restyled said would fix it, but it wouldn't complete because it said it was an empty patch.  Also it seems like the original file I was working with wouldn't have worked either, because it modified stuff I did not touch.

**Comment by wotanut** [comment]
Wow, thanks for the hard work. I know this is old, but i'll check over it shortly and then merge it over the weekend.

**Comment by wotanut** [comment]
So, i'm not sure if this is an issue with BD or with the way the plugin handles settings, but it's currently not possible to open the settings page.
Screenshot 2024-10-14 at 11 03 37

Error code: https://react.dev/errors/31?invariant=31&args%5B%5D=object+with+keys+%7Blisteners%2C+element%2C+onChange%7D

Will fix later when I have some more time

**Comment by Firefly7-7** [comment]
Ah, my apologies at some point I fixed this error and forgot to commit.  The fix is just adding a `.GetElement` on the return statement.

**Comment by wotanut** [comment]
Thanks for that, i've just updated the capitilisation so that getElement is correct (it was originally GetElement which was causing an object error when opening settings)

**Comment by wotanut** [comment]
Once again, apologies for being so slow.

**Pull request merged**
