### PR TITLE
Added Spotify

### PR DESCRIPTION
**Pull request by NDDDDDDDDD**
Not that many changes, but I added Spotify to the plugin. This will remove the tracking url from playlists, albums, tracks, artits and users. Nothing else has been changed

### CODE REVIEW

**Comment by wotanut** [comment]
This is great, but can you commit the source as well please?

**Comment by NDDDDDDDDD** [comment]
> This is great, but can you commit the source as well please?

Updated the src file!

**Comment by wotanut** [comment]
This is great, thank you for this. I forgot to ask you to increment the version and stuff but it's not really a big deal...I hope.

**Comment by NDDDDDDDDD** [comment]
> This is great, thank you for this. I forgot to ask you to increment the version and stuff but it's not really a big deal...I hope.

ah yeah my bad

**Pull request merged**
